In [1]:
import numpy as np

In [2]:
n1 = np.array([10,20,30,40])

In [3]:
print(n1)

[10 20 30 40]


In [4]:
type(n1)

numpy.ndarray

# initialization a array of matrix 

In [5]:
n2= np.array([[]])

In [21]:

n3 = np.full((3,3),9)

In [7]:
n3

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

# Initializtion of NumPy array within a range.

In [11]:
n5 = np.arange(10,20)

In [12]:
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
## array with the skip

In [15]:
n6 = np.arange(1,10,2)

In [16]:
n6

array([1, 3, 5, 7, 9])

# initialization NumPy array with the random

In [18]:
n7 = np.random.randint(100,1000,10)

In [19]:
n7

array([418, 461, 365, 545, 940, 823, 315, 890, 282, 967])

In [22]:
n5,n7


(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([418, 461, 365, 545, 940, 823, 315, 890, 282, 967]))

In [32]:
n7 = np.random.randint(1000,9999,1)
print(n7)

[1235]


array([6552])

# Initilization the array shape changes in the fraction 

In [43]:
n8 = np.array([[10,20,30],[40,50,60],[70,80,90],[22,23,24]])

In [44]:
n8

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [22, 23, 24]])

In [47]:
n8.shape=(4,3)

In [48]:
n8

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [22, 23, 24]])

# Joining NumPy Array

In [50]:
a = np.array([10,20,30])
b = np.array([40,50,60])

In [51]:
np.vstack((a,b)) #joining the numpy as vertical stacking

array([[10, 20, 30],
       [40, 50, 60]])

In [52]:
np.hstack((a,b)) #joining the numpy as horizontal stacking

array([10, 20, 30, 40, 50, 60])

In [53]:
np.column_stack((a,b)) #joining the numpy as column stacking

array([[10, 40],
       [20, 50],
       [30, 60]])

In [54]:
np.row_stack((a,b)) #joining the numpy as row stacking

array([[10, 20, 30],
       [40, 50, 60]])

# NumPy Intersection and difference

In [57]:
x = np.array([10,20,30,40,50,60])
y = np.array([30,50,90,100,120,150])

In [58]:
np.intersect1d(x,y)

array([30, 50])

In [2]:
import pandas as pd


In [3]:
s1 = pd.Series([1,2,3,4,5])